name: Publish Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add proper permissions for the workflow
permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    # Add permissions for this specific job
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.13.1
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build package
      run: pnpm run build
      
    - name: Check if version changed
      id: version-check
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        PUBLISHED_VERSION=$(npm view @mfissehaye/telebirr-utils version 2>/dev/null || echo "0.0.0")
        echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "published=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT
        if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Version changed from $PUBLISHED_VERSION to $CURRENT_VERSION"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "Version unchanged: $CURRENT_VERSION"
        fi
        
    - name: Publish to npm
      if: steps.version-check.outputs.changed == 'true'
      run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release
      if: steps.version-check.outputs.changed == 'true'
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ steps.version-check.outputs.current }}
        name: Release v${{ steps.version-check.outputs.current }}
        body: |
          🚀 **Release v${{ steps.version-check.outputs.current }}**
          
          ### What's Changed
          See the [README](./README.md) for package documentation.
          
          ### Installation
          ```bash
          npm install @mfissehaye/telebirr-utils
          ```
          
          ---
          *This release was automatically generated by GitHub Actions*
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}